version: '3'
services:
  student_service:
    image: nginx
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017/student_db
    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: student_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
